// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topic.proto

package com.odib.bcp.im.mars.sample.chat.proto;

public final class Topic {
  private Topic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopicRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.odib.bcp.im.mars.sample.chat.proto.TopicRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string topic = 1;</code>
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();
  }
  /**
   * Protobuf type {@code com.odib.bcp.im.mars.sample.chat.proto.TopicRequest}
   */
  public  static final class TopicRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.odib.bcp.im.mars.sample.chat.proto.TopicRequest)
      TopicRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopicRequest.newBuilder() to construct.
    private TopicRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopicRequest() {
      topic_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TopicRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              topic_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.class, com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object topic_;
    /**
     * <code>required string topic = 1;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest)) {
        return super.equals(obj);
      }
      com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest other = (com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest) obj;

      boolean result = true;
      result = result && (hasTopic() == other.hasTopic());
      if (hasTopic()) {
        result = result && getTopic()
            .equals(other.getTopic());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTopic()) {
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopic().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.odib.bcp.im.mars.sample.chat.proto.TopicRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.odib.bcp.im.mars.sample.chat.proto.TopicRequest)
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.class, com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.Builder.class);
      }

      // Construct using com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_descriptor;
      }

      public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest getDefaultInstanceForType() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.getDefaultInstance();
      }

      public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest build() {
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest buildPartial() {
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest result = new com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest) {
          return mergeFrom((com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest other) {
        if (other == com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          bitField0_ |= 0x00000001;
          topic_ = other.topic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTopic()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object topic_ = "";
      /**
       * <code>required string topic = 1;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.odib.bcp.im.mars.sample.chat.proto.TopicRequest)
    }

    // @@protoc_insertion_point(class_scope:com.odib.bcp.im.mars.sample.chat.proto.TopicRequest)
    private static final com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest();
    }

    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TopicRequest>
        PARSER = new com.google.protobuf.AbstractParser<TopicRequest>() {
      public TopicRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopicRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopicRequest> getParserForType() {
      return PARSER;
    }

    public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TopicResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.odib.bcp.im.mars.sample.chat.proto.TopicResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 err_code = 1;</code>
     */
    boolean hasErrCode();
    /**
     * <code>required int32 err_code = 1;</code>
     */
    int getErrCode();

    /**
     * <code>required string err_msg = 2;</code>
     */
    boolean hasErrMsg();
    /**
     * <code>required string err_msg = 2;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>required string err_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();
  }
  /**
   * Protobuf type {@code com.odib.bcp.im.mars.sample.chat.proto.TopicResponse}
   */
  public  static final class TopicResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.odib.bcp.im.mars.sample.chat.proto.TopicResponse)
      TopicResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopicResponse.newBuilder() to construct.
    private TopicResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopicResponse() {
      errCode_ = 0;
      errMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TopicResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.class, com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code com.odib.bcp.im.mars.sample.chat.proto.TopicResponse.Error}
     */
    public enum Error
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ERR_OK = 0;</code>
       */
      ERR_OK(0),
      /**
       * <code>ERR_SYS = -1;</code>
       */
      ERR_SYS(-1),
      ;

      /**
       * <code>ERR_OK = 0;</code>
       */
      public static final int ERR_OK_VALUE = 0;
      /**
       * <code>ERR_SYS = -1;</code>
       */
      public static final int ERR_SYS_VALUE = -1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Error valueOf(int value) {
        return forNumber(value);
      }

      public static Error forNumber(int value) {
        switch (value) {
          case 0: return ERR_OK;
          case -1: return ERR_SYS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Error>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Error> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Error>() {
              public Error findValueByNumber(int number) {
                return Error.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Error[] VALUES = values();

      public static Error valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Error(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.odib.bcp.im.mars.sample.chat.proto.TopicResponse.Error)
    }

    private int bitField0_;
    public static final int ERR_CODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <code>required int32 err_code = 1;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 err_code = 1;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int ERR_MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object errMsg_;
    /**
     * <code>required string err_msg = 2;</code>
     */
    public boolean hasErrMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string err_msg = 2;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string err_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasErrCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse)) {
        return super.equals(obj);
      }
      com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse other = (com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse) obj;

      boolean result = true;
      result = result && (hasErrCode() == other.hasErrCode());
      if (hasErrCode()) {
        result = result && (getErrCode()
            == other.getErrCode());
      }
      result = result && (hasErrMsg() == other.hasErrMsg());
      if (hasErrMsg()) {
        result = result && getErrMsg()
            .equals(other.getErrMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrCode()) {
        hash = (37 * hash) + ERR_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasErrMsg()) {
        hash = (37 * hash) + ERR_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.odib.bcp.im.mars.sample.chat.proto.TopicResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.odib.bcp.im.mars.sample.chat.proto.TopicResponse)
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.class, com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.Builder.class);
      }

      // Construct using com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_descriptor;
      }

      public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse getDefaultInstanceForType() {
        return com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.getDefaultInstance();
      }

      public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse build() {
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse buildPartial() {
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse result = new com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errMsg_ = errMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse) {
          return mergeFrom((com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse other) {
        if (other == com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse.getDefaultInstance()) return this;
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrMsg()) {
          bitField0_ |= 0x00000002;
          errMsg_ = other.errMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrCode()) {
          return false;
        }
        if (!hasErrMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int errCode_ ;
      /**
       * <code>required int32 err_code = 1;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 err_code = 1;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>required int32 err_code = 1;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000001;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 err_code = 1;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>required string err_msg = 2;</code>
       */
      public boolean hasErrMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string err_msg = 2;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string err_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string err_msg = 2;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string err_msg = 2;</code>
       */
      public Builder clearErrMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string err_msg = 2;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.odib.bcp.im.mars.sample.chat.proto.TopicResponse)
    }

    // @@protoc_insertion_point(class_scope:com.odib.bcp.im.mars.sample.chat.proto.TopicResponse)
    private static final com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse();
    }

    public static com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TopicResponse>
        PARSER = new com.google.protobuf.AbstractParser<TopicResponse>() {
      public TopicResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopicResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopicResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopicResponse> getParserForType() {
      return PARSER;
    }

    public com.odib.bcp.im.mars.sample.chat.proto.Topic.TopicResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013topic.proto\022&com.odib.bcp.im.mars.samp" +
      "le.chat.proto\"\035\n\014TopicRequest\022\r\n\005topic\030\001" +
      " \002(\t\"]\n\rTopicResponse\022\020\n\010err_code\030\001 \002(\005\022" +
      "\017\n\007err_msg\030\002 \002(\t\")\n\005Error\022\n\n\006ERR_OK\020\000\022\024\n" +
      "\007ERR_SYS\020\377\377\377\377\377\377\377\377\377\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicRequest_descriptor,
        new java.lang.String[] { "Topic", });
    internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_odib_bcp_im_mars_sample_chat_proto_TopicResponse_descriptor,
        new java.lang.String[] { "ErrCode", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
